openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8081
  description: Generated server url
paths:
  /api/user/test:
    get:
      tags:
      - account-controller
      operationId: test
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RestBeanAccount'
components:
  schemas:
    Account:
      type: object
    RestBeanAccount:
      type: object
      properties:
        code:
          type: integer
          format: int32
        data:
          $ref: '#/components/schemas/Account'
        message:
          type: string
